spring.application.name=SpringAIDemo
#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-3.5-turbo


#spring.ai.google.genai.api-key=AQ.Ab8RN6K0VH9eR5bb88mvjOP7js988uSuXSmBfGqHbsKHAt4_9g
# Optional: Set a specific model if needed
#spring.ai.google.genai.chat.options.model=gemini-3.5-flash
spring.kafka.bootstrap-servers=localhost:9092
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
logging.level.org.springframework.ai.chat=TRACE